DROP TABLE has_skill CASCADE CONSTRAINTS;
DROP TABLE takes CASCADE CONSTRAINTS;
DROP TABLE prereq CASCADE CONSTRAINTS;
DROP TABLE teaches CASCADE CONSTRAINTS;
DROP TABLE requires CASCADE CONSTRAINTS;
DROP TABLE req_by_job CASCADE CONSTRAINTS;
DROP TABLE line_item CASCADE CONSTRAINTS;
DROP TABLE sales CASCADE CONSTRAINTS;
DROP TABLE payment_record CASCADE CONSTRAINTS;
DROP TABLE person CASCADE CONSTRAINTS;
DROP TABLE course CASCADE CONSTRAINTS;
DROP TABLE section CASCADE CONSTRAINTS;
DROP TABLE skill CASCADE CONSTRAINTS;
DROP TABLE position CASCADE CONSTRAINTS;
DROP TABLE job CASCADE CONSTRAINTS;
DROP TABLE store CASCADE CONSTRAINTS;
DROP TABLE inventory CASCADE CONSTRAINTS;
DROP TABLE supplier CASCADE CONSTRAINTS;
DROP TABLE account_payable CASCADE CONSTRAINTS;


COMMIT;