DROP TABLE has_skill CASCADE CONSTRAINTS;
DROP TABLE takes CASCADE CONSTRAINTS;
DROP TABLE prereq CASCADE CONSTRAINTS;
DROP TABLE teaches CASCADE CONSTRAINTS;
DROP TABLE req_by_job CASCADE CONSTRAINTS;
DROP TABLE requires CASCADE CONSTRAINTS;
DROP TABLE works CASCADE CONSTRAINTS;
DROP TABLE sub_industry CASCADE CONSTRAINTS;
DROP TABLE hires CASCADE CONSTRAINTS;
DROP TABLE person CASCADE CONSTRAINTS;
DROP TABLE course CASCADE CONSTRAINTS;
DROP TABLE section CASCADE CONSTRAINTS;
DROP TABLE skill CASCADE CONSTRAINTS;
DROP TABLE company CASCADE CONSTRAINTS;
DROP TABLE gics CASCADE CONSTRAINTS;
DROP TABLE job CASCADE CONSTRAINTS;
DROP TABLE position CASCADE CONSTRAINTS;

COMMIT;